### ISSUE TITLE
sha256sums.sig 404 not found

### ISSUE THREAD

**Issue by gramimoss** [aparcar/meta-imagebuilder#8]
Looks like openwrt have removed sha256sums.sig from the downloads. 

The script now fails and can't update firmware Test results are from the following attended upgrade https://chef.libremesh.org/download/faillogs/faillog-ee2a0cc4e782.txt

Please could look into this. you have done an amazing job would be great have a working script.

**Comment by aparcar** [comment]
Please try again, should be fixed!

**Comment by gramimoss** [comment]
> Please try again, should be fixed!

Hi Thanks for an amazing response. I tried on the luci-app no luck and I also tried manually the result is the same https://chef.libremesh.org/download/faillogs/faillog-5c4e9fb1e267.txt

Still failing to download the sig file which stops the build.

**Comment by aparcar** [comment]
Sorry I did not update the metabuilder script on the chef server. Please try again.

**Comment by gramimoss** [comment]
> Sorry I did not update the metabuilder script on the chef server. Please try again.

Awesome, HAHAHA "You are in the build queue. Position: 4935" I guess it's got a backlog from people trying :)

So I tested the script on my laptop it gets past the sig file problem. I just now have a package problem where iw is trying to install but it looks like they changed the package to iw-full. 
```
 * check_data_file_clashes: Package iw wants to install file /home/graeme/openwrt_meta/imagebuilder/openwrt/18.06.2/ar71xx/generic/build_dir/target-mips_24kc_musl/root-ar71xx/usr/sbin/iw
	But that file is already provided by package  * iw-full
 * opkg_install_cmd: Cannot install package iw.
```

Will try fix that on my side. Thank you for fixing this. keep up the work this project is amazing!

**Comment by aparcar** [comment]
I started to generate Docker images, if you use Docker please give it a try. Hopefully this somewhat improves reproducibility:

    sudo docker run --rm -it openwrt-metabuilder:alpine

**Comment by aparcar** [comment]
@gramimoss can I close this issue?
